### ISSUE TITLE
一些值得记录的知识点

### ISSUE THREAD

**Issue by amenzai** [amenzai/myDiary#78]
### 空格字符
当中文和英文混杂的时候，使用`&ensp;`, `&emsp;`等空格实现冒号的完美对齐还是有些困难的，除非英文使用的是等宽字体，于是乎，我们就可以使用普通的`&nbsp;`空格做英文字符的宽度调节。

再科普点关于字符的实用知识吧：

1. HTML中字符输出使用`&#x`配上charCode值；
2. 在JavaScript文件中为防止乱码转义，则是`\u`配上charCode值；
3. 而在CSS文件中，如CSS伪元素的`content`属性，直接使用`\`配上charCode值。

因此，想在`HTML/JS/CSS`中转义“我”这个汉字，分别是：

1. `&#x6211;`
2. `\u6211`, 如`console.log('\u6211');`
3. `\6211`, 如`.xxx:before { content: '\6211'; }`

考虑到直接`&#x3000;`这种形式暴露在HTML中，可能会让屏幕阅读器等辅助设备读取，从而影响正常阅读流，因此，我们可以进一步优化下，使用标签，利用伪元素，例如：

```css
.half:before { content: '\2002'; speak: none; }
.full:before { content: '\2003'; speak: none; }
```
